package com.pickagent.w2.reliability;

import java.util.Objects;

/**
 * Returns the first successful result for a stable operation key and request.
 *
 * <p>Only successful results are cached. If the operation throws, the store is
 * unchanged and a later call may try again. Therefore operations whose failure
 * can occur after a side effect still need a transactional or provider-side
 * idempotency boundary in production.</p>
 *
 * @param <R> operation result type
 */
public final class IdempotentExecutor<R> {
    /**
     * An operation that may fail before producing a cacheable result.
     *
     * @param <R> operation result type
     */
    @FunctionalInterface
    public interface Operation<R> {
        /**
         * Runs the underlying operation.
         *
         * @return operation result
         * @throws Exception when the operation cannot produce a result
         */
        R execute() throws Exception;
    }

    /** Raised when one operation key is reused for a different logical request. */
    public static final class IdempotencyConflictException extends IllegalStateException {
        /**
         * Creates a conflict with a diagnostic message.
         *
         * @param message conflict detail
         */
        public IdempotencyConflictException(String message) {
            super(message);
        }
    }

    private final IdempotencyStore<R> store;

    /**
     * Creates an executor backed by the supplied store.
     *
     * @param store successful-result store
     */
    public IdempotentExecutor(IdempotencyStore<R> store) {
        this.store = Objects.requireNonNull(store, "store");
    }

    /**
     * Executes once after a cache miss, or replays the first successful result.
     *
     * @param operationKey stable key generated by the application
     * @param requestFingerprint stable fingerprint of the logical request
     * @param operation underlying side-effecting operation
     * @return first successful result for this key and request
     * @throws Exception when an uncached operation fails
     */
    public R execute(String operationKey, String requestFingerprint, Operation<R> operation)
            throws Exception {
        requireNonBlank(operationKey, "operationKey");
        requireNonBlank(requestFingerprint, "requestFingerprint");
        Objects.requireNonNull(operation, "operation");

        var existing = store.find(operationKey);
        if (existing.isPresent()) {
            var entry = existing.orElseThrow();
            if (!entry.requestFingerprint().equals(requestFingerprint)) {
                throw new IdempotencyConflictException(
                        "operationKey already belongs to a different request: " + operationKey);
            }
            return entry.result();
        }

        R result = operation.execute();
        store.save(operationKey, new IdempotencyStore.Entry<>(requestFingerprint, result));
        return result;
    }

    private static void requireNonBlank(String value, String field) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException(field + " cannot be null or blank");
        }
    }
}
